### ISSUE TITLE
EDA

### ISSUE THREAD

**Issue by uowol** [uowol/Titanic-Data-Visualization#1]
### Todo List 
- [x] 사전작업 - 각 feature의 형태 파악
- [x] 전처리 - 파생 변수의 고려
- [x] 전처리 - 결측치 처리
